--!strict
-- Run-scoped and account-scoped progression: XP/level within a run, permanent
-- talent unlocks in the hub, and the relic pick flow at floor transitions.
-- Also owns the "build readout" data the HUD's active-relic tray reads -
-- Balatro-style legibility means the server should already know which
-- archetype tags are active and how strongly, not leave the client to infer it.
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Types = require(ReplicatedStorage.Shared.Types)
local Relics = require(ReplicatedStorage.Shared.Data.Relics)
local Talents = require(ReplicatedStorage.Shared.Data.Talents)
local Remotes = require(ReplicatedStorage.Shared.Modules.Remotes)

local ProgressionService = {}

export type RunProgression = {
	equippedRelics: { string },
	archetypeTagCounts: { [string]: number }, -- drives both relic-offer bias (LootService) and the HUD synergy readout
	xp: number,
	level: number,
}

export type AccountProgression = {
	unlockedTalents: { [string]: boolean },
}

local runProgressions: { [number]: RunProgression } = {}
local accountProgressions: { [number]: AccountProgression } = {}
local RemotesFolder: Folder

local function newRunProgression(): RunProgression
	return { equippedRelics = {}, archetypeTagCounts = {}, xp = 0, level = 1 }
end

function ProgressionService.StartRun(player: Player)
	runProgressions[player.UserId] = newRunProgression()
end

function ProgressionService.GetRun(player: Player): RunProgression
	local progression = runProgressions[player.UserId]
	assert(progression, "GetRun called with no active run - StartRun must be called first")
	return progression
end

function ProgressionService.GetAccount(player: Player): AccountProgression
	local progression = accountProgressions[player.UserId]
	if not progression then
		progression = { unlockedTalents = {} }
		accountProgressions[player.UserId] = progression
	end
	return progression
end

-- Presents the floor-transition relic offer and applies the player's pick.
-- The offer itself is generated by LootService (weighted by archetype bias);
-- ProgressionService owns validating the pick came from the actual offer,
-- not an arbitrary relic id the client injects.
local pendingOffers: { [number]: { Types.RelicDef } } = {}

function ProgressionService.PresentRelicOffer(player: Player, offer: { Types.RelicDef })
	pendingOffers[player.UserId] = offer
	local event = Remotes.Get(RemotesFolder, "RelicOfferPresented") :: RemoteEvent
	event:FireClient(player, {
		relics = offer,
	})
end

local function onRequestSelectRelic(player: Player, relicId: string?)
	if typeof(relicId) ~= "string" then
		return
	end
	local offer = pendingOffers[player.UserId]
	if not offer then
		return
	end
	local chosen: Types.RelicDef? = nil
	for _, relic in offer do
		if relic.id == relicId then
			chosen = relic
			break
		end
	end
	if not chosen then
		return -- client tried to pick a relic that wasn't actually offered
	end

	local run = ProgressionService.GetRun(player)
	table.insert(run.equippedRelics, chosen.id)
	for _, tag in chosen.archetypeTags do
		run.archetypeTagCounts[tag] = (run.archetypeTagCounts[tag] or 0) + 1
	end
	pendingOffers[player.UserId] = nil

	ProgressionService._pushUpdate(player)
end

local function onRequestSelectTalent(player: Player, talentId: string?)
	if typeof(talentId) ~= "string" then
		return
	end
	local talent = Talents[talentId]
	if not talent then
		return
	end
	local account = ProgressionService.GetAccount(player)
	for _, prereq in talent.prerequisites do
		if not account.unlockedTalents[prereq] then
			return -- prerequisite gate enforced server-side, never trust client-side tree-state
		end
	end
	-- Currency cost check delegates to EconomyService before unlocking;
	-- omitted here to keep this module focused on tree-state validity.
	account.unlockedTalents[talentId] = true
	ProgressionService._pushUpdate(player)
end

function ProgressionService._pushUpdate(player: Player)
	local event = Remotes.Get(RemotesFolder, "ProgressionUpdated") :: RemoteEvent
	local run = runProgressions[player.UserId]
	local account = ProgressionService.GetAccount(player)
	event:FireClient(player, {
		equippedRelics = run and run.equippedRelics or {},
		archetypeTagCounts = run and run.archetypeTagCounts or {},
		unlockedTalents = account.unlockedTalents,
	})
end

function ProgressionService.Init(remotesFolder: Folder)
	RemotesFolder = remotesFolder
	(Remotes.Get(remotesFolder, "RequestSelectRelic") :: RemoteEvent).OnServerEvent:Connect(onRequestSelectRelic)
	(Remotes.Get(remotesFolder, "RequestSelectTalent") :: RemoteEvent).OnServerEvent:Connect(onRequestSelectTalent)

	Players.PlayerRemoving:Connect(function(player)
		runProgressions[player.UserId] = nil
		pendingOffers[player.UserId] = nil
	end)
end

return ProgressionService
