--[[
	WeaponData
	Single source of truth for every weapon's stats. Read by both server
	(DamageService / WeaponServer, authoritative) and client (WeaponController,
	cosmetic/prediction only). Never let the client mutate this table.
]]

local WeaponData = {}

-- FireMode: "Auto" | "Burst" | "Semi"
WeaponData.Weapons = {
	VantaRifle = {
		Id = "VantaRifle",
		DisplayName = "Vanta Rifle",
		Slot = "Primary",
		FireMode = "Auto",
		Damage = 28,
		HeadshotMultiplier = 2.0,
		FireRate = 8, -- rounds per second
		Magazine = 25,
		ReloadTime = 2.1,
		Range = 100,
		Spread = 1.6,
		ADSSpread = 0.4,
		MoveSpeedMultiplier = 0.94,
		ADSMoveSpeedMultiplier = 0.8,
		ADSZoomFOV = 65,
		Recoil = { Vertical = 1.4, Horizontal = 0.5, Recovery = 6 },
		Color = Color3.fromRGB(60, 140, 255),
	},
	NovaSMG = {
		Id = "NovaSMG",
		DisplayName = "Nova SMG",
		Slot = "Primary",
		FireMode = "Auto",
		Damage = 18,
		HeadshotMultiplier = 2.0,
		FireRate = 14,
		Magazine = 30,
		ReloadTime = 1.8,
		Range = 55,
		Spread = 2.4,
		ADSSpread = 0.9,
		MoveSpeedMultiplier = 1.0,
		ADSMoveSpeedMultiplier = 0.88,
		ADSZoomFOV = 68,
		Recoil = { Vertical = 0.9, Horizontal = 0.7, Recovery = 8 },
		Color = Color3.fromRGB(150, 90, 255),
	},
	ApexBurst = {
		Id = "ApexBurst",
		DisplayName = "Apex Burst",
		Slot = "Primary",
		FireMode = "Burst",
		BurstCount = 3,
		BurstRate = 14,
		Damage = 32,
		HeadshotMultiplier = 2.0,
		FireRate = 3, -- bursts per second
		Magazine = 21,
		ReloadTime = 2.3,
		Range = 90,
		Spread = 1.1,
		ADSSpread = 0.3,
		MoveSpeedMultiplier = 0.95,
		ADSMoveSpeedMultiplier = 0.82,
		ADSZoomFOV = 63,
		Recoil = { Vertical = 1.8, Horizontal = 0.4, Recovery = 5 },
		Color = Color3.fromRGB(70, 180, 255),
	},
	RiftShotgun = {
		Id = "RiftShotgun",
		DisplayName = "Rift Shotgun",
		Slot = "Primary",
		FireMode = "Semi",
		Pellets = 8,
		DamagePerPellet = 12,
		HeadshotMultiplier = 1.5,
		FireRate = 1.1,
		Magazine = 6,
		ReloadTime = 2.6,
		Range = 30,
		Spread = 6,
		ADSSpread = 3.5,
		MoveSpeedMultiplier = 0.9,
		ADSMoveSpeedMultiplier = 0.8,
		ADSZoomFOV = 72,
		Recoil = { Vertical = 3.2, Horizontal = 1.5, Recovery = 5 },
		Color = Color3.fromRGB(180, 70, 255),
	},
	EchoMarksman = {
		Id = "EchoMarksman",
		DisplayName = "Echo Marksman",
		Slot = "Primary",
		FireMode = "Semi",
		Damage = 55,
		HeadshotMultiplier = 2.5,
		FireRate = 2,
		Magazine = 10,
		ReloadTime = 2.4,
		Range = 150,
		Spread = 0.3,
		ADSSpread = 0.05,
		MoveSpeedMultiplier = 0.9,
		ADSMoveSpeedMultiplier = 0.7,
		ADSZoomFOV = 45,
		Recoil = { Vertical = 2.6, Horizontal = 0.3, Recovery = 7 },
		Color = Color3.fromRGB(100, 200, 255),
	},
	VoidLMG = {
		Id = "VoidLMG",
		DisplayName = "Void LMG",
		Slot = "Primary",
		FireMode = "Auto",
		Damage = 24,
		HeadshotMultiplier = 1.8,
		FireRate = 10,
		Magazine = 60,
		ReloadTime = 3.4,
		Range = 95,
		Spread = 2.2,
		ADSSpread = 0.8,
		MoveSpeedMultiplier = 0.82,
		ADSMoveSpeedMultiplier = 0.6,
		ADSZoomFOV = 68,
		Recoil = { Vertical = 1.6, Horizontal = 0.9, Recovery = 5 },
		Color = Color3.fromRGB(120, 60, 200),
	},

	PulsePistol = {
		Id = "PulsePistol",
		DisplayName = "Pulse Pistol",
		Slot = "Secondary",
		FireMode = "Semi",
		Damage = 20,
		HeadshotMultiplier = 2.0,
		FireRate = 6,
		Magazine = 16,
		ReloadTime = 1.5,
		Range = 60,
		Spread = 1.4,
		ADSSpread = 0.5,
		MoveSpeedMultiplier = 1.0,
		ADSMoveSpeedMultiplier = 0.9,
		ADSZoomFOV = 66,
		Recoil = { Vertical = 1.0, Horizontal = 0.4, Recovery = 8 },
		Color = Color3.fromRGB(80, 160, 255),
	},
	MagnumX = {
		Id = "MagnumX",
		DisplayName = "Magnum-X",
		Slot = "Secondary",
		FireMode = "Semi",
		Damage = 45,
		HeadshotMultiplier = 2.5,
		FireRate = 1.8,
		Magazine = 6,
		ReloadTime = 2.0,
		Range = 80,
		Spread = 0.8,
		ADSSpread = 0.2,
		MoveSpeedMultiplier = 0.97,
		ADSMoveSpeedMultiplier = 0.85,
		ADSZoomFOV = 60,
		Recoil = { Vertical = 3.0, Horizontal = 0.6, Recovery = 6 },
		Color = Color3.fromRGB(160, 80, 255),
	},
	MicroSMG = {
		Id = "MicroSMG",
		DisplayName = "Micro SMG",
		Slot = "Secondary",
		FireMode = "Auto",
		Damage = 14,
		HeadshotMultiplier = 2.0,
		FireRate = 16,
		Magazine = 20,
		ReloadTime = 1.4,
		Range = 35,
		Spread = 3.0,
		ADSSpread = 1.2,
		MoveSpeedMultiplier = 1.02,
		ADSMoveSpeedMultiplier = 0.92,
		ADSZoomFOV = 70,
		Recoil = { Vertical = 0.7, Horizontal = 0.8, Recovery = 9 },
		Color = Color3.fromRGB(190, 100, 255),
	},

	PhaseBlade = {
		Id = "PhaseBlade",
		DisplayName = "Phase Blade",
		Slot = "Melee",
		FireMode = "Melee",
		Damage = 65,
		Range = 7,
		FireRate = 1.6,
		Color = Color3.fromRGB(190, 60, 255),
	},
}

WeaponData.Loadout = {
	Primary = "VantaRifle",
	Secondary = "PulsePistol",
	Melee = "PhaseBlade",
}

function WeaponData.Get(weaponId)
	return WeaponData.Weapons[weaponId]
end

return WeaponData
