--!strict
-- Molten Forge: the third biome, reached through the Fungal Depths' scorched
-- lower vent. Identity: an abandoned industrial forge-complex still half-
-- running on its own momentum - aggressive, loud, and actively hostile
-- terrain rather than just hostile enemies. Mechanical hook: hazard tiles
-- (lava pools, collapsing floor sections) are a second combatant in every
-- fight, and knockback/positioning against them is core kit for every
-- archetype here. Generated with a hazard-grid pass layered on top of BSP:
-- rooms are still planned industrial spaces, but a second generation pass
-- marks a subset of floor tiles as collapsing/lava per floor's hazardDensity,
-- which is why this biome alone lists "HazardGrid" as its algorithm rather
-- than reusing the Crypt's plain BSP.
local Types = require(script.Parent.Parent.Types)

local MoltenForge: Types.BiomeDef = {
	id = "MoltenForge",
	displayName = "The Molten Forge",
	identity = "An industrial forge-complex left to run itself long after the last smith died. "
		.. "Tone is aggressive and loud - hammering, distant metal groans, structural failure as "
		.. "ambience. Mechanical hook is terrain-as-combatant: lava pools and collapsing floor "
		.. "sections generated by a hazard-grid pass mean positioning against the room matters as "
		.. "much as positioning against the enemy. Palette is rust-orange and cooling-slag black "
		.. "against dull hot-metal glow; audio is rhythmic distant hammering that syncs with the "
		.. "combat layer's percussion when a fight starts.",
	generationAlgorithm = "HazardGrid",
	bossId = "ForgeheartColossus",
	ambientLoopId = "Amb_Molten_HammerDrone",
	combatLayerId = "Combat_Molten_Layer",
	fogColor = Color3.fromRGB(38, 20, 14),
	fogEnd = 75,
	primaryMaterialPalette = { Enum.Material.CorrodedMetal, Enum.Material.Basalt, Enum.Material.Metal },
	accentColor = Color3.fromRGB(214, 96, 42),
	floors = {
		{
			floorIndex = 1,
			tierLabel = "Cooling Vents",
			minRooms = 11,
			maxRooms = 15,
			enemyTierRange = { 3, 3 },
			spawnTable = {
				{ enemyId = "CinderWisp", weight = 45 },
				{ enemyId = "SlagBrute", weight = 30 },
				{ enemyId = "ForgeboundSentinel", weight = 25 },
			},
			hazardDensity = 0.15,
			vaultChance = 0.15,
			isBossFloor = false,
		},
		{
			floorIndex = 2,
			tierLabel = "The Slag Stair",
			minRooms = 12,
			maxRooms = 16,
			enemyTierRange = { 3, 3 },
			spawnTable = {
				{ enemyId = "SlagBrute", weight = 40 },
				{ enemyId = "CinderWisp", weight = 35 },
				{ enemyId = "ForgeboundSentinel", weight = 25 },
			},
			hazardDensity = 0.22,
			vaultChance = 0.18,
			isBossFloor = false,
		},
		{
			floorIndex = 3,
			tierLabel = "Cinder Works",
			minRooms = 12,
			maxRooms = 17,
			enemyTierRange = { 3, 3 },
			spawnTable = {
				{ enemyId = "SlagBrute", weight = 35 },
				{ enemyId = "CinderWisp", weight = 35 },
				{ enemyId = "ForgeboundSentinel", weight = 30 },
			},
			hazardDensity = 0.3,
			vaultChance = 0.2,
			isBossFloor = false,
		},
		{
			floorIndex = 4,
			tierLabel = "Anvil Deep",
			minRooms = 13,
			maxRooms = 17,
			enemyTierRange = { 3, 3 },
			spawnTable = {
				{ enemyId = "ForgeboundSentinel", weight = 35 },
				{ enemyId = "SlagBrute", weight = 35 },
				{ enemyId = "CinderWisp", weight = 30 },
			},
			hazardDensity = 0.35,
			vaultChance = 0.2,
			isBossFloor = false,
		},
		{
			floorIndex = 5,
			tierLabel = "The Bellows",
			minRooms = 13,
			maxRooms = 18,
			enemyTierRange = { 3, 3 },
			spawnTable = {
				{ enemyId = "SlagBrute", weight = 35 },
				{ enemyId = "ForgeboundSentinel", weight = 35 },
				{ enemyId = "CinderWisp", weight = 30 },
			},
			hazardDensity = 0.4, -- densest hazard coverage in the game before the boss
			vaultChance = 0.25,
			isBossFloor = false,
		},
		{
			floorIndex = 6,
			tierLabel = "Forgeheart",
			minRooms = 1,
			maxRooms = 1,
			enemyTierRange = { 3, 3 },
			spawnTable = {},
			hazardDensity = 0.2, -- boss arena keeps hazard tiles active, see BossPhaseDef FloorIgnition
			vaultChance = 0,
			isBossFloor = true,
		},
	},
}

return MoltenForge
